// ============================================================
// Unity 側で prefab を組み立てる C# エディタスクリプト（テンプレート）
// ------------------------------------------------------------
// .prefab の YAML を手書きすると、Unity / TextMeshPro のバージョン差で
// GUID やシリアライズ形式が合わずに参照が壊れる。
// そこで prefab の組み立ては Unity 内で本物の API に任せ、
// こちらは「レイアウト JSON + PNG + このスクリプト」だけを渡す。
//
// 出力先は Assets/<CardName>/Editor/ProxyzCardImporter.cs。
// "Editor" フォルダ配下に置くことで Unity がエディタ拡張として
// コンパイルする（ビルドには含まれない）。
// ============================================================

export const UNITY_IMPORTER_CS = String.raw`// Generated by Proxyz - https://proxyz.synapstudio.com
// カードのレイアウト JSON から Prefab を組み立てるエディタ拡張です。
// メニュー: Tools > Proxyz > カードを Prefab にする

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using TMPro;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

namespace Proxyz.EditorTools
{
    [Serializable]
    public class ProxyzLayer
    {
        public string name;
        public string kind;        // "image" | "text" | "textbg"
        public string component;   // "auto" | "quad" | "sprite" | "tmp3d" | "tmpUgui" | "skip"

        // カード座標系（px・左上原点）
        public float centerX;
        public float centerY;
        public float width;
        public float height;
        public float rotation;     // 度・時計回りが正
        public float opacity = 1f;

        // 画像用
        public string image;       // JSON からの相対パス。空なら無し

        // テキスト用
        public string text;
        public float fontSize;
        public bool bold;
        public string align;       // "left" | "center" | "right"
        public string colorHex;
    }

    [Serializable]
    public class ProxyzCard
    {
        public string cardName;
        public float canvasWidth;
        public float canvasHeight;
        public float pixelsPerUnit = 100f;
        public string mode;        // "2d" | "3d"
        public ProxyzLayer[] layers;
    }

    public class ProxyzCardImporter : EditorWindow
    {
        private TextAsset _json;
        private DefaultAsset _folder;
        private TMP_FontAsset _font;
        private int _modeIndex = -1;                 // -1 = JSON の指定に従う
        private readonly string[] _modeLabels = { "JSON の指定に従う", "2D（Sprite + Canvas）", "3D（Quad + TextMeshPro）" };
        private Vector2 _scroll;
        private string _message = "";
        private MessageType _messageType = MessageType.None;

        [MenuItem("Tools/Proxyz/カードを Prefab にする")]
        public static void Open()
        {
            var window = GetWindow<ProxyzCardImporter>(true, "Proxyz カードインポータ");
            window.minSize = new Vector2(420, 320);
            window.TryAutoDetect();
        }

        private void TryAutoDetect()
        {
            if (_json == null)
            {
                // プロジェクト内の card.json を 1 つだけ見つけたら自動で入れる
                var guids = AssetDatabase.FindAssets("card t:TextAsset");
                var found = new List<TextAsset>();
                foreach (var guid in guids)
                {
                    var path = AssetDatabase.GUIDToAssetPath(guid);
                    if (!path.EndsWith("card.json", StringComparison.OrdinalIgnoreCase)) continue;
                    var asset = AssetDatabase.LoadAssetAtPath<TextAsset>(path);
                    if (asset != null) found.Add(asset);
                }
                if (found.Count == 1) _json = found[0];
            }

            if (_font == null)
            {
                // 日本語を含むフォントアセットを優先して探す
                var guids = AssetDatabase.FindAssets("t:TMP_FontAsset");
                TMP_FontAsset firstAny = null;
                foreach (var guid in guids)
                {
                    var path = AssetDatabase.GUIDToAssetPath(guid);
                    var asset = AssetDatabase.LoadAssetAtPath<TMP_FontAsset>(path);
                    if (asset == null) continue;
                    if (firstAny == null) firstAny = asset;
                    // "LiberationSans" 以外を優先（日本語フォントの可能性が高い）
                    if (path.IndexOf("LiberationSans", StringComparison.OrdinalIgnoreCase) < 0)
                    {
                        _font = asset;
                        break;
                    }
                }
                if (_font == null) _font = firstAny;
            }
        }

        private void OnGUI()
        {
            _scroll = EditorGUILayout.BeginScrollView(_scroll);

            EditorGUILayout.LabelField("Proxyz カード → Prefab", EditorStyles.boldLabel);
            EditorGUILayout.Space();

            _folder = (DefaultAsset)EditorGUILayout.ObjectField(
                new GUIContent("カードフォルダ（一括）", "ProxyzCards フォルダを指定すると、配下のカードをまとめて Prefab 化します"),
                _folder, typeof(DefaultAsset), false);

            _json = (TextAsset)EditorGUILayout.ObjectField(
                new GUIContent("レイアウト JSON（単体）", "1 枚だけ生成したい場合は card.json を指定"),
                _json, typeof(TextAsset), false);

            _font = (TMP_FontAsset)EditorGUILayout.ObjectField(
                new GUIContent("TMP フォントアセット", "日本語を表示するには日本語対応のフォントアセットを指定してください"),
                _font, typeof(TMP_FontAsset), false);

            _modeIndex = EditorGUILayout.Popup("書き出しモード", _modeIndex + 1, _modeLabels) - 1;

            EditorGUILayout.Space();

            if (_font == null)
            {
                EditorGUILayout.HelpBox(
                    "TMP フォントアセットが未指定です。テキストは既定フォントで生成され、日本語が豆腐（□）になる可能性があります。",
                    MessageType.Warning);
            }

            using (new EditorGUI.DisabledScope(_json == null && _folder == null))
            {
                if (GUILayout.Button("Prefab を生成", GUILayout.Height(32)))
                {
                    Build();
                }
            }

            if (!string.IsNullOrEmpty(_message))
            {
                EditorGUILayout.Space();
                EditorGUILayout.HelpBox(_message, _messageType);
            }

            EditorGUILayout.EndScrollView();
        }

        // ------------------------------------------------------------
        // 生成本体
        // ------------------------------------------------------------

        private void Build()
        {
            // ドロップ直後などで未インポートのファイルが残っていないよう、
            // 先にアセットデータベースを最新化しておく
            AssetDatabase.Refresh();

            // 処理対象の card.json を集める。
            // フォルダ指定があれば配下を全部、無ければ単体指定の 1 件。
            var targets = new List<TextAsset>();
            if (_folder != null)
            {
                var folderPath = AssetDatabase.GetAssetPath(_folder);
                var guids = AssetDatabase.FindAssets("card t:TextAsset", new[] { folderPath });
                foreach (var guid in guids)
                {
                    var path = AssetDatabase.GUIDToAssetPath(guid);
                    if (!path.EndsWith("card.json", StringComparison.OrdinalIgnoreCase)) continue;
                    var asset = AssetDatabase.LoadAssetAtPath<TextAsset>(path);
                    if (asset != null) targets.Add(asset);
                }
                if (targets.Count == 0)
                {
                    SetMessage("指定フォルダ内に card.json が見つかりませんでした。", MessageType.Warning);
                    return;
                }
            }
            else if (_json != null)
            {
                targets.Add(_json);
            }
            else
            {
                SetMessage("カードフォルダか card.json を指定してください。", MessageType.Warning);
                return;
            }

            var results = new List<string>();
            var failed = 0;
            foreach (var target in targets)
            {
                var prefabPath = BuildOne(target);
                if (prefabPath != null) results.Add(prefabPath);
                else failed++;
            }

            if (results.Count > 0)
            {
                var first = AssetDatabase.LoadAssetAtPath<GameObject>(results[0]);
                if (first != null)
                {
                    EditorGUIUtility.PingObject(first);
                    Selection.activeObject = first;
                }
            }

            var msg = results.Count + " 件の Prefab を生成しました";
            if (failed > 0) msg += "（" + failed + " 件失敗 — Console を確認してください）";
            if (results.Count > 0) msg += ":\n" + string.Join("\n", results.ToArray());
            SetMessage(msg, failed > 0 ? MessageType.Warning : MessageType.Info);
        }

        /// <summary>card.json 1 件を Prefab 化する。成功時は Prefab のパス、失敗時は null。</summary>
        private string BuildOne(TextAsset jsonAsset)
        {
            GameObject root = null;
            try
            {
                var jsonPath = AssetDatabase.GetAssetPath(jsonAsset);
                var folder = Path.GetDirectoryName(jsonPath).Replace("\\", "/");
                var card = JsonUtility.FromJson<ProxyzCard>(jsonAsset.text);

                if (card == null || card.layers == null)
                {
                    Debug.LogError("[Proxyz] JSON を読み取れませんでした: " + jsonPath);
                    return null;
                }

                var mode = _modeIndex < 0 ? (card.mode ?? "2d") : (_modeIndex == 0 ? "2d" : "3d");
                var ppu = card.pixelsPerUnit > 0f ? card.pixelsPerUnit : 100f;
                var cw = card.canvasWidth;
                var ch = card.canvasHeight;

                var rootName = string.IsNullOrEmpty(card.cardName) ? "ProxyzCard" : card.cardName;
                root = new GameObject(rootName);

                // UGUI 要素（テキスト / ボタン）用のワールド空間 Canvas。
                // 必要になったら 1 つだけ作る
                GameObject uiRoot = null;
                GameObject EnsureUiRoot()
                {
                    if (uiRoot != null) return uiRoot;
                    uiRoot = new GameObject("UI");
                    uiRoot.transform.SetParent(root.transform, false);
                    var canvas = uiRoot.AddComponent<Canvas>();
                    canvas.renderMode = RenderMode.WorldSpace;
                    canvas.sortingOrder = 100;
                    // ボタンのクリック判定に必要
                    uiRoot.AddComponent<GraphicRaycaster>();
                    var canvasRect = uiRoot.GetComponent<RectTransform>();
                    canvasRect.sizeDelta = new Vector2(cw, ch);
                    canvasRect.localPosition = Vector3.zero;
                    canvasRect.localRotation = Quaternion.identity;
                    canvasRect.localScale = Vector3.one / ppu;
                    return uiRoot;
                }

                var sortingOrder = 0;
                var createdMaterials = new List<string>();

                foreach (var layer in card.layers)
                {
                    if (layer == null || layer.component == "skip") continue;

                    var resolved = ResolveComponent(layer, mode);
                    if (resolved == "skip") continue;

                    var localRot = Quaternion.Euler(0f, 0f, -layer.rotation);
                    var pos = ToUnityPos(layer.centerX, layer.centerY, cw, ch, ppu, -0.001f * sortingOrder);

                    // ---------- 画像 / テキスト背景 ----------
                    if (layer.kind == "image" || layer.kind == "textbg")
                    {
                        if (string.IsNullOrEmpty(layer.image))
                        {
                            Debug.LogWarning("[Proxyz] 画像パスが未設定のためスキップします: " + layer.name);
                            continue;
                        }
                        var assetPath = folder + "/" + layer.image;

                        // ---- ボタン（UGUI: Image + Button）----
                        if (resolved == "button")
                        {
                            var btnSprite = LoadSprite(assetPath, ppu);
                            if (btnSprite == null)
                            {
                                Debug.LogWarning("[Proxyz] スプライトが見つかりません: " + assetPath);
                                continue;
                            }
                            var ui = EnsureUiRoot();
                            var btnGo = new GameObject(layer.name);
                            btnGo.transform.SetParent(ui.transform, false);
                            var btnImage = btnGo.AddComponent<Image>();
                            btnImage.sprite = btnSprite;
                            var bic = btnImage.color;
                            bic.a = Mathf.Clamp01(layer.opacity);
                            btnImage.color = bic;
                            btnGo.AddComponent<Button>().targetGraphic = btnImage;
                            var btnRect = btnGo.GetComponent<RectTransform>();
                            btnRect.pivot = new Vector2(0.5f, 0.5f);
                            btnRect.anchorMin = new Vector2(0.5f, 0.5f);
                            btnRect.anchorMax = new Vector2(0.5f, 0.5f);
                            btnRect.sizeDelta = new Vector2(layer.width, layer.height);
                            btnRect.anchoredPosition = new Vector2(layer.centerX - cw / 2f, ch / 2f - layer.centerY);
                            btnRect.localRotation = localRot;
                            sortingOrder++;
                            continue;
                        }

                        var go = new GameObject(layer.name);
                        go.transform.SetParent(root.transform, false);

                        if (resolved == "quad")
                        {
                            var tex = LoadTexture(assetPath);
                            if (tex == null)
                            {
                                Debug.LogWarning("[Proxyz] テクスチャが見つかりません: " + assetPath);
                                DestroyImmediate(go);
                                continue;
                            }
                            var mat = CreateMaterial(folder, layer.name, tex, layer.opacity, createdMaterials);
                            var mf = go.AddComponent<MeshFilter>();
                            mf.sharedMesh = GetQuadMesh();
                            var mr = go.AddComponent<MeshRenderer>();
                            mr.sharedMaterial = mat;
                            mr.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
                            mr.receiveShadows = false;
                            mr.sortingOrder = sortingOrder;

                            go.transform.localPosition = pos;
                            go.transform.localRotation = localRot;
                            go.transform.localScale = new Vector3(layer.width / ppu, layer.height / ppu, 1f);
                        }
                        else // sprite
                        {
                            var sprite = LoadSprite(assetPath, ppu);
                            if (sprite == null)
                            {
                                Debug.LogWarning("[Proxyz] スプライトが見つかりません: " + assetPath);
                                DestroyImmediate(go);
                                continue;
                            }
                            var sr = go.AddComponent<SpriteRenderer>();
                            sr.sprite = sprite;
                            sr.sortingOrder = sortingOrder;
                            var c = sr.color;
                            c.a = Mathf.Clamp01(layer.opacity);
                            sr.color = c;

                            // スプライトの実寸に対して、指定サイズになるよう個別にスケールする
                            var nativeW = sprite.rect.width;
                            var nativeH = sprite.rect.height;
                            go.transform.localPosition = pos;
                            go.transform.localRotation = localRot;
                            go.transform.localScale = new Vector3(
                                nativeW > 0f ? layer.width / nativeW : 1f,
                                nativeH > 0f ? layer.height / nativeH : 1f,
                                1f);
                        }

                        sortingOrder++;
                        continue;
                    }

                    // ---------- テキスト ----------
                    if (layer.kind == "text")
                    {
                        // ---- テキストボタン（UGUI: Image + Button + 子 TMP ラベル）----
                        if (resolved == "button")
                        {
                            var ui = EnsureUiRoot();
                            var btnGo = new GameObject(layer.name);
                            btnGo.transform.SetParent(ui.transform, false);
                            var btnImage = btnGo.AddComponent<Image>();
                            if (!string.IsNullOrEmpty(layer.image))
                            {
                                var bgSprite = LoadSprite(folder + "/" + layer.image, ppu);
                                if (bgSprite != null) btnImage.sprite = bgSprite;
                            }
                            else
                            {
                                // 見た目なしでもクリック判定は受けたいので透明にする
                                btnImage.color = new Color(1f, 1f, 1f, 0f);
                            }
                            btnGo.AddComponent<Button>().targetGraphic = btnImage;
                            var btnRect = btnGo.GetComponent<RectTransform>();
                            btnRect.pivot = new Vector2(0.5f, 0.5f);
                            btnRect.anchorMin = new Vector2(0.5f, 0.5f);
                            btnRect.anchorMax = new Vector2(0.5f, 0.5f);
                            btnRect.sizeDelta = new Vector2(layer.width, layer.height);
                            btnRect.anchoredPosition = new Vector2(layer.centerX - cw / 2f, ch / 2f - layer.centerY);
                            btnRect.localRotation = localRot;

                            var labelGo = new GameObject(layer.name + "_Label");
                            labelGo.transform.SetParent(btnGo.transform, false);
                            var label = labelGo.AddComponent<TextMeshProUGUI>();
                            if (_font != null) label.font = _font;
                            label.text = layer.text ?? "";
                            label.fontSize = layer.fontSize;
                            label.color = ParseColor(layer.colorHex, 1f);
                            label.fontStyle = layer.bold ? FontStyles.Bold : FontStyles.Normal;
                            label.alignment = TextAlignmentOptions.Center;
                            label.overflowMode = TextOverflowModes.Overflow;
                            label.richText = false;
                            var labelRect = labelGo.GetComponent<RectTransform>();
                            labelRect.anchorMin = Vector2.zero;
                            labelRect.anchorMax = Vector2.one;
                            labelRect.offsetMin = Vector2.zero;
                            labelRect.offsetMax = Vector2.zero;

                            sortingOrder++;
                            continue;
                        }

                        var isUgui = resolved == "tmpUgui";

                        if (isUgui) EnsureUiRoot();

                        var go = new GameObject(layer.name);
                        go.transform.SetParent(isUgui ? uiRoot.transform : root.transform, false);

                        TMP_Text tmp;
                        if (isUgui) tmp = go.AddComponent<TextMeshProUGUI>();
                        else tmp = go.AddComponent<TextMeshPro>();

                        if (_font != null) tmp.font = _font;
                        tmp.text = layer.text ?? "";
                        tmp.fontSize = layer.fontSize;
                        tmp.color = ParseColor(layer.colorHex, layer.opacity);
                        tmp.fontStyle = layer.bold ? FontStyles.Bold : FontStyles.Normal;
                        tmp.alignment = ToAlignment(layer.align);
                        tmp.overflowMode = TextOverflowModes.Overflow;
                        tmp.richText = false;

                        var rect = go.GetComponent<RectTransform>();
                        // 中央基準で配置する。ピボットは中央固定にして、
                        // 左右寄せは TMP の alignment 側で表現する
                        rect.pivot = new Vector2(0.5f, 0.5f);
                        rect.anchorMin = new Vector2(0.5f, 0.5f);
                        rect.anchorMax = new Vector2(0.5f, 0.5f);
                        rect.localRotation = localRot;

                        if (isUgui)
                        {
                            // UGUI の TMP は「フォントサイズ 1pt = Canvas 1px」なので
                            // px の値をそのまま使える
                            rect.sizeDelta = new Vector2(layer.width + 8f, layer.height + 8f);
                            rect.anchoredPosition = new Vector2(layer.centerX - cw / 2f, ch / 2f - layer.centerY);
                            rect.localScale = Vector3.one;
                        }
                        else
                        {
                            // ワールド空間の TMP は「フォントサイズ 10pt = 1 ユニット」で
                            // 描画される（UGUI の 10 倍細かい）。px 基準に合わせるため
                            // rect をローカル 1/10 で組み、全体を 10/ppu 倍する。
                            // → 実サイズ: fontSize(px)/10 × 10/ppu = fontSize/ppu で px と一致
                            rect.sizeDelta = new Vector2((layer.width + 8f) / 10f, (layer.height + 8f) / 10f);
                            rect.localPosition = pos;
                            rect.localScale = Vector3.one * (10f / ppu);
                            var mr = go.GetComponent<MeshRenderer>();
                            if (mr != null) mr.sortingOrder = sortingOrder;
                        }

                        sortingOrder++;
                    }
                }

                // ---------- Prefab として保存 ----------
                var outDir = folder + "/Prefabs";
                if (!AssetDatabase.IsValidFolder(outDir))
                {
                    AssetDatabase.CreateFolder(folder, "Prefabs");
                }
                var prefabPath = AssetDatabase.GenerateUniqueAssetPath(outDir + "/" + rootName + ".prefab");
                PrefabUtility.SaveAsPrefabAsset(root, prefabPath);
                AssetDatabase.SaveAssets();
                AssetDatabase.Refresh();

                return prefabPath;
            }
            catch (Exception e)
            {
                Debug.LogError("[Proxyz] 生成に失敗しました: " + AssetDatabase.GetAssetPath(jsonAsset));
                Debug.LogException(e);
                return null;
            }
            finally
            {
                if (root != null) DestroyImmediate(root);
            }
        }

        // ------------------------------------------------------------
        // ヘルパー
        // ------------------------------------------------------------

        private static string ResolveComponent(ProxyzLayer layer, string mode)
        {
            var c = string.IsNullOrEmpty(layer.component) ? "auto" : layer.component;
            if (c == "button" || c == "skip") return c;
            // 旧バージョンの書き出しに含まれる詳細指定もそのまま解釈する
            if (c == "quad" || c == "sprite" || c == "tmp3d" || c == "tmpUgui") return c;
            // auto: モードから決める
            if (layer.kind == "image" || layer.kind == "textbg")
                return mode == "3d" ? "quad" : "sprite";
            return mode == "3d" ? "tmp3d" : "tmpUgui";
        }

        private static Vector3 ToUnityPos(float px, float py, float cw, float ch, float ppu, float z)
        {
            return new Vector3((px - cw / 2f) / ppu, (ch / 2f - py) / ppu, z);
        }

        /// <summary>
        /// パス文字列の照合に頼らず、実在するテクスチャに到達できるパスを解決する。
        /// Unicode 正規化差（NFC/NFD）などで AssetDatabase がパスを引けない
        /// ケースを、段階的なフォールバックで回避する。解決できなければ null。
        /// </summary>
        private static string ResolveTexturePath(string assetPath)
        {
            // 1. そのまま引く
            if (AssetImporter.GetAtPath(assetPath) as TextureImporter != null) return assetPath;

            // 2. NFC 正規化して引く
            var normalized = assetPath.Normalize(NormalizationForm.FormC);
            if (normalized != assetPath &&
                AssetImporter.GetAtPath(normalized) as TextureImporter != null)
            {
                return normalized;
            }

            // 3. 明示的にインポートしてから引く
            if (File.Exists(assetPath))
            {
                AssetDatabase.ImportAsset(assetPath,
                    ImportAssetOptions.ForceUpdate | ImportAssetOptions.ForceSynchronousImport);
                if (AssetImporter.GetAtPath(assetPath) as TextureImporter != null) return assetPath;
            }

            // 4. フォルダを Unity 側から走査し、Unity 自身が持つパス文字列を採用する。
            //    （入力パスと DB 内パスの表記が食い違っていても、GUID 経由で取った
            //      パスなら必ず一致する）
            var dir = Path.GetDirectoryName(assetPath);
            if (!string.IsNullOrEmpty(dir))
            {
                dir = dir.Replace("\\", "/");
                var wanted = Path.GetFileName(assetPath).Normalize(NormalizationForm.FormC);
                if (AssetDatabase.IsValidFolder(dir))
                {
                    var guids = AssetDatabase.FindAssets("t:Texture2D", new[] { dir });
                    foreach (var guid in guids)
                    {
                        var candidate = AssetDatabase.GUIDToAssetPath(guid);
                        var candidateName = Path.GetFileName(candidate).Normalize(NormalizationForm.FormC);
                        if (string.Equals(candidateName, wanted, StringComparison.OrdinalIgnoreCase))
                        {
                            return candidate;
                        }
                    }
                }
            }

            // 5. 最終手段: ASCII 名で複製してインポートする。
            //    ファイル自体は正常でも、ファイル名が原因で Unity のインポート
            //    パイプラインに乗らないケースを確実に回避する。
            if (File.Exists(assetPath) && !string.IsNullOrEmpty(dir))
            {
                var hash = 0;
                foreach (var ch in Path.GetFileName(assetPath)) hash = hash * 31 + ch;
                var copyPath = dir + "/px_" + (hash & 0x7fffffff).ToString("x8") + Path.GetExtension(assetPath);
                try
                {
                    if (!File.Exists(copyPath)) File.Copy(assetPath, copyPath);
                    AssetDatabase.ImportAsset(copyPath,
                        ImportAssetOptions.ForceUpdate | ImportAssetOptions.ForceSynchronousImport);
                    if (AssetImporter.GetAtPath(copyPath) as TextureImporter != null)
                    {
                        Debug.LogWarning("[Proxyz] ファイル名の問題を回避するため複製して取り込みました: " +
                            assetPath + " → " + copyPath);
                        return copyPath;
                    }
                }
                catch (Exception e)
                {
                    Debug.LogException(e);
                }
            }

            return null;
        }

        /// <summary>テクスチャ解決に完全に失敗したときの診断ログ</summary>
        private static void LogTextureFailure(string assetPath)
        {
            if (!File.Exists(assetPath))
            {
                Debug.LogError("[Proxyz] 原因: ファイルがディスク上に存在しません（ZIP の展開漏れ or パス不一致）: " + assetPath);
                return;
            }
            string detail;
            try
            {
                var info = new FileInfo(assetPath);
                var head = new byte[8];
                int read;
                using (var fs = File.OpenRead(assetPath))
                {
                    read = fs.Read(head, 0, 8);
                }
                var isPng = read >= 8 &&
                    head[0] == 0x89 && head[1] == 0x50 &&
                    head[2] == 0x4E && head[3] == 0x47;
                detail = "サイズ=" + info.Length + "バイト, PNGシグネチャ=" +
                    (isPng ? "正常" : "異常（PNG として壊れています）");
            }
            catch (Exception ex)
            {
                detail = "ファイル読み取り失敗: " + ex.Message;
            }
            Debug.LogError("[Proxyz] 原因: 全フォールバックを試しましたが Unity がこのファイルを認識できません。" +
                detail + " : " + assetPath);
        }

        private static Sprite LoadSprite(string assetPath, float ppu)
        {
            var resolved = ResolveTexturePath(assetPath);
            if (resolved == null)
            {
                LogTextureFailure(assetPath);
                return null;
            }
            assetPath = resolved;

            var importer = AssetImporter.GetAtPath(assetPath) as TextureImporter;
            if (importer != null)
            {
                var dirty = false;
                // 注意: textureType を Sprite にするだけでは足りない。
                // スクリプト経由だと spriteImportMode が None のままになり、
                // Sprite サブアセットが生成されない。
                if (importer.textureType != TextureImporterType.Sprite ||
                    importer.spriteImportMode != SpriteImportMode.Single)
                {
                    importer.textureType = TextureImporterType.Sprite;
                    importer.spriteImportMode = SpriteImportMode.Single;
                    dirty = true;
                }
                if (!Mathf.Approximately(importer.spritePixelsPerUnit, ppu))
                {
                    importer.spritePixelsPerUnit = ppu;
                    dirty = true;
                }
                if (!importer.alphaIsTransparency)
                {
                    importer.alphaIsTransparency = true;
                    dirty = true;
                }
                if (importer.mipmapEnabled)
                {
                    importer.mipmapEnabled = false;
                    dirty = true;
                }
                if (importer.maxTextureSize < 4096)
                {
                    importer.maxTextureSize = 4096;
                    dirty = true;
                }
                if (dirty) importer.SaveAndReimport();
            }

            var sprite = AssetDatabase.LoadAssetAtPath<Sprite>(assetPath);
            if (sprite == null && importer != null)
            {
                Debug.LogError("[Proxyz] 原因: インポート済みなのに Sprite が生成されていません。textureType=" +
                    importer.textureType + " / spriteImportMode=" + importer.spriteImportMode + ": " + assetPath);
            }
            return sprite;
        }

        private static Texture2D LoadTexture(string assetPath)
        {
            var resolved = ResolveTexturePath(assetPath);
            if (resolved == null)
            {
                LogTextureFailure(assetPath);
                return null;
            }
            assetPath = resolved;

            var importer = AssetImporter.GetAtPath(assetPath) as TextureImporter;
            if (importer != null)
            {
                var dirty = false;
                if (importer.textureType != TextureImporterType.Default)
                {
                    importer.textureType = TextureImporterType.Default;
                    dirty = true;
                }
                if (!importer.alphaIsTransparency)
                {
                    importer.alphaIsTransparency = true;
                    dirty = true;
                }
                if (importer.maxTextureSize < 4096)
                {
                    importer.maxTextureSize = 4096;
                    dirty = true;
                }
                if (dirty) importer.SaveAndReimport();
            }
            return AssetDatabase.LoadAssetAtPath<Texture2D>(assetPath);
        }


        /// <summary>Unity 組み込みの Quad メッシュを取得する</summary>
        private static Mesh GetQuadMesh()
        {
            var temp = GameObject.CreatePrimitive(PrimitiveType.Quad);
            var mesh = temp.GetComponent<MeshFilter>().sharedMesh;
            DestroyImmediate(temp);
            return mesh;
        }

        private static Material CreateMaterial(
            string folder, string name, Texture2D tex, float opacity, List<string> created)
        {
            var matDir = folder + "/Materials";
            if (!AssetDatabase.IsValidFolder(matDir))
            {
                AssetDatabase.CreateFolder(folder, "Materials");
            }

            // Sprites/Default はビルトインでも URP でも動作する
            var shader = Shader.Find("Sprites/Default");
            if (shader == null) shader = Shader.Find("Unlit/Transparent");
            if (shader == null) shader = Shader.Find("Standard");

            var mat = new Material(shader) { name = name };
            mat.mainTexture = tex;
            if (mat.HasProperty("_Color"))
            {
                mat.color = new Color(1f, 1f, 1f, Mathf.Clamp01(opacity));
            }

            var path = AssetDatabase.GenerateUniqueAssetPath(matDir + "/" + SanitizeFileName(name) + ".mat");
            AssetDatabase.CreateAsset(mat, path);
            created.Add(path);
            return AssetDatabase.LoadAssetAtPath<Material>(path);
        }

        private static string SanitizeFileName(string name)
        {
            foreach (var c in Path.GetInvalidFileNameChars())
            {
                name = name.Replace(c, '_');
            }
            return string.IsNullOrEmpty(name) ? "Layer" : name;
        }

        private static Color ParseColor(string hex, float alpha)
        {
            var color = Color.white;
            if (!string.IsNullOrEmpty(hex))
            {
                var h = hex.TrimStart('#');
                if (h.Length == 3)
                {
                    h = string.Concat(h[0], h[0], h[1], h[1], h[2], h[2]);
                }
                if (h.Length >= 6 &&
                    int.TryParse(h.Substring(0, 2), NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var r) &&
                    int.TryParse(h.Substring(2, 2), NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var g) &&
                    int.TryParse(h.Substring(4, 2), NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var b))
                {
                    color = new Color(r / 255f, g / 255f, b / 255f);
                }
            }
            color.a = Mathf.Clamp01(alpha <= 0f ? 1f : alpha);
            return color;
        }

        private static TextAlignmentOptions ToAlignment(string align)
        {
            switch (align)
            {
                case "left": return TextAlignmentOptions.Left;
                case "right": return TextAlignmentOptions.Right;
                default: return TextAlignmentOptions.Center;
            }
        }

        private void SetMessage(string message, MessageType type)
        {
            _message = message;
            _messageType = type;
            Repaint();
        }
    }
}
`;